// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_narwhal_blast = "CgkI1ZL9iP0bEAIQBQ"; // <GPGSID>
        public const string achievement_nine = "CgkI1ZL9iP0bEAIQDA"; // <GPGSID>
        public const string achievement_ten = "CgkI1ZL9iP0bEAIQDQ"; // <GPGSID>
        public const string achievement_this_is_getting_out_of_hand = "CgkI1ZL9iP0bEAIQBA"; // <GPGSID>
        public const string achievement_come_on = "CgkI1ZL9iP0bEAIQDw"; // <GPGSID>
        public const string achievement_you_are_still_too_weak = "CgkI1ZL9iP0bEAIQEw"; // <GPGSID>
        public const string achievement_thats_rough_buddy = "CgkI1ZL9iP0bEAIQBg"; // <GPGSID>
        public const string achievement_cook = "CgkI1ZL9iP0bEAIQEA"; // <GPGSID>
        public const string achievement_you_have_all_the_power_in_the_world = "CgkI1ZL9iP0bEAIQEg"; // <GPGSID>
        public const string achievement_hundred = "CgkI1ZL9iP0bEAIQDg"; // <GPGSID>
        public const string achievement_hey_big_spender = "CgkI1ZL9iP0bEAIQCA"; // <GPGSID>
        public const string achievement_field_of_hopes_and_dreams = "CgkI1ZL9iP0bEAIQCQ"; // <GPGSID>
        public const string achievement_king_of_the_week = "CgkI1ZL9iP0bEAIQCg"; // <GPGSID>
        public const string achievement_dream_on = "CgkI1ZL9iP0bEAIQEQ"; // <GPGSID>
        public const string achievement_poland_cannot_into_space = "CgkI1ZL9iP0bEAIQBw"; // <GPGSID>
        public const string achievement_eight = "CgkI1ZL9iP0bEAIQCw"; // <GPGSID>
        public const string leaderboard_score_leaderboard = "CgkI1ZL9iP0bEAIQAg"; // <GPGSID>

}

