// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_time_objective = "CgkIhKWF3_MQEAIQAw"; // <GPGSID>
        public const string achievement_water_tribe = "CgkIhKWF3_MQEAIQEQ"; // <GPGSID>
        public const string achievement_nine = "CgkIhKWF3_MQEAIQCA"; // <GPGSID>
        public const string achievement_you_have_all_the_power_in_the_world = "CgkIhKWF3_MQEAIQFA"; // <GPGSID>
        public const string achievement_this_is_getting_out_of_hand = "CgkIhKWF3_MQEAIQCg"; // <GPGSID>
        public const string achievement_narwhal_blast = "CgkIhKWF3_MQEAIQEA"; // <GPGSID>
        public const string achievement_come_on = "CgkIhKWF3_MQEAIQCw"; // <GPGSID>
        public const string achievement_you_are_still_too_weak = "CgkIhKWF3_MQEAIQFQ"; // <GPGSID>
        public const string achievement_ten = "CgkIhKWF3_MQEAIQCQ"; // <GPGSID>
        public const string achievement_cook = "CgkIhKWF3_MQEAIQDg"; // <GPGSID>
        public const string achievement_hundred = "CgkIhKWF3_MQEAIQDA"; // <GPGSID>
        public const string achievement_thats_rough_buddy = "CgkIhKWF3_MQEAIQEg"; // <GPGSID>
        public const string achievement_dream_on = "CgkIhKWF3_MQEAIQDw"; // <GPGSID>
        public const string achievement_hey_big_spender = "CgkIhKWF3_MQEAIQBg"; // <GPGSID>
        public const string achievement_score_objective = "CgkIhKWF3_MQEAIQAQ"; // <GPGSID>
        public const string achievement_field_of_hopes_and_dreams = "CgkIhKWF3_MQEAIQDQ"; // <GPGSID>
        public const string achievement_coin_objective = "CgkIhKWF3_MQEAIQAg"; // <GPGSID>
        public const string achievement_poland_cannot_into_space = "CgkIhKWF3_MQEAIQEw"; // <GPGSID>
        public const string achievement_eight = "CgkIhKWF3_MQEAIQBw"; // <GPGSID>
        public const string leaderboard_score_leaderboard = "CgkIhKWF3_MQEAIQFg"; // <GPGSID>

}

